// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvfgmcmqfjxaaabkxyla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2ZmdtY21xZmp4YWFhYmt4eWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzI5MjQsImV4cCI6MjA3MzEwODkyNH0.dNMLq4bQyciCEdzhqrj4VGWhNHRYmxmD43MMhYrslkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});